///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace @new
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the newRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("6515808d-b5c3-4aff-aa93-3d15c474ccf1")]
    public partial class newRepository : RepoGenBaseFolder
    {
        static newRepository instance = new newRepository();

        /// <summary>
        /// Gets the singleton class instance representing the newRepository element repository.
        /// </summary>
        [RepositoryFolder("6515808d-b5c3-4aff-aa93-3d15c474ccf1")]
        public static newRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public newRepository() 
            : base("newRepository", "/", null, 0, false, "6515808d-b5c3-4aff-aa93-3d15c474ccf1", ".\\RepositoryImages\\newRepository6515808d.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6515808d-b5c3-4aff-aa93-3d15c474ccf1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class newRepositoryFolders
    {
    }
#pragma warning restore 0436
}